# Generated by Django 4.2.20 on 2025-04-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('FINISHED', 'finished')], default='pending', max_length=50),
        ),
    ]
