# Generated by Django 4.2.19 on 2025-02-25 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todolist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='name',
            new_name='task',
        ),
    ]
